<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <InvariantGlobalization>true</InvariantGlobalization>
    <PublishAot>true</PublishAot>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\Tyuiu.TinkovSS.Sprint0.Task7.V0.Lib\Tyuiu.TinkovSS.Sprint0.Task7.V0.Lib.csproj" />
  </ItemGroup>

</Project>
